# Generated by Django 3.2.5 on 2021-07-02 19:51

from django.db import migrations, models
import django.db.models.deletion
import todos_app.todos.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Home', 'Home stuff'), ('Work', 'Work stuff')], max_length=20)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'people',
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, validators=[todos_app.todos.validators.validate_dot])),
                ('state', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('categories', models.ManyToManyField(to='todos.Category')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todos.person')),
            ],
        ),
    ]
